### ISSUE TITLE
The distributed package contains optional chaining (?.) operator which is not supported by node < 14

### ISSUE THREAD

**Issue by alvis** [lightyen/rollup-plugin-tsconfig-paths#1]
Since node 12 is still in active LTS until 2022, shall we make `rollup-plugin-ts-paths-resolve` more widely supported by introducing `@babel/preset-env` in the build chain?

**Comment by lightyen** [comment]
https://github.com/lightyen/rollup-plugin-tsconfig-paths/commit/06666199108d9b14764b8dc5a20a74b83aa68903
